### ISSUE TITLE
Player in to Map-Layer

### ISSUE THREAD

**Issue by Fruchtgummi** [SolarLune/goaseprite#2]
How I get a Player in a Map-Layer?

![image](https://user-images.githubusercontent.com/2059888/56473728-8068a580-646f-11e9-923f-f717b64a4e96.png)

If I would going to a wall, the be upstanding the player on top the wall.

![image](https://user-images.githubusercontent.com/2059888/56473766-0c7acd00-6470-11e9-963f-5a63f87f7841.png)

![image](https://user-images.githubusercontent.com/2059888/56473774-1c92ac80-6470-11e9-8445-9aeb971f0956.png)

**Comment by SolarLune** [comment]
goaseprite is a Golang library for importing Aseprite files, not anything to do with Tiled. I'm not certain I understand your question, but if you don't want to have your player character intersect with wall objects, then you need to define those objects in Tiled, import them into your game engine / framework, and then make some method of collision to ensure that they don't intersect.

**Comment by Fruchtgummi** [comment]
I use goraylib, your goaseprite, github.com/salviati/go-tmx/tmx and orient me after her testgame. https://twitter.com/solarlune/status/1001140401716117504

I think goasprite issues, is the wrong gategorie for my question. sry...

**Comment by SolarLune** [comment]
No, no problem! I'll go ahead and close this now.
